---
- name: Install apt-transport-https
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add weechat repository gpg-key
  become: true
  ansible.builtin.apt_key:
    keyserver: 'keys.openpgp.org'
    id: "{{ weechat__gpg_id }}"
    state: present

- name: Add weechat repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb {{ weechat__debian_weechat_repo }}"
    state: present
    update_cache: true

- name: Add weechat repo-src
  become: true
  ansible.builtin.apt_repository:
    repo: "deb-src {{ weechat__debian_weechat_repo }}"
    state: present
    update_cache: true

- name: Install recomended weechat packages
  become: true
  ansible.builtin.apt:
    name:
      - weechat-curses
      - weechat-plugins
      - weechat-python
      - weechat-perl
      - weechat-lua
      - weechat-ruby
      - weechat-doc
    state: present
