---
- name: Perform optinal versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when: submodules_versioncheck | bool

- name: 'Install weechat'
  ansible.builtin.include_tasks:
    file: "install-{{ ansible_os_family | lower }}.yml"
  when: weechat__install | bool

- name: 'Deploy weechat__configuration'
  ansible.builtin.include_tasks:
    file: configure_custom_config.yml
  when: weechat__use_custom_config | bool

- name: 'Install requirements for weechat__plugins'
  ansible.builtin.include_tasks:
    file: configure_plugins.yml
  when: weechat__install_plugins | bool

- name: 'Setup weechat__autostart'
  ansible.builtin.include_tasks:
    file: setup_autostart.yml
  when: weechat__autostart | bool
